---
- hosts: webservers
  become: true

  tasks:
   
    - name: log into docker hub registry
      docker_login:
        username: "vinaymg006"
        password: "Vinay64$."

    - name: ensure a container is running
      docker_container:
        name: my_container
        state: started
        image: "vinaymg006/webapp:${BUILD_NUMBER}"
        pull: true
        ports:
          - "8080:8080"
