
   
- hosts: webserver
  become: True 
  tasks:
   - name: Install python pip 
     yum:
       name: python-pip
       state: present
   - name: Install docker-py python module 
     pip:
        name: docker-py 
        state: present
   - name: Start the container 
     docker_container:
        name: hariapp
        image: 
        state: started 
        published ports:
        - 0.0.0.0:8080:8080
